## Correr con:
## docker build -f Dockerfile.password -t IMAGE-NAME .
FROM alpine

#RUN mkdir /app
#RUN apk update

#RUN echo "123" | doas apk add bash
RUN doas apk add bash
RUN echo "usuario:1234" | chpasswd
RUN export KEY="1234"

USER usuario

#WORKDIR /app

#COPY package*.json ./

#COPY . .

#RUN apk add nodejs
#RUN apk add npm
#RUN npm install

EXPOSE 3000
EXPOSE 3443

#CMD ["npm","start"]
CMD sh
