## Correr con:
## docker build -f Dockerfile.backup -t IMAGE-NAME .
## alpine es una imagen de DockerHub

FROM alpine

RUN mkdir /app

WORKDIR /app

#COPY package*.json ./

COPY . .

#RUN apk add nodejs
#RUN apk add npm
#RUN npm install

EXPOSE 3000
EXPOSE 3443

#CMD ["npm","start"]
