## Correr con:
## docker build -f Dockerfile.alpine -t IMAGE-NAME .
## alpine es una imagen de DockerHub

FROM alpine

RUN mkdir /app

WORKDIR /app

#COPY package*.json ./

COPY . .
RUN apk add nodejs
RUN apk add npm

EXPOSE 3000
EXPOSE 3443

#RUN npm install

CMD ["npm","start"]
